# generate by script/dep
buffer.o: buffer.h
event.o: event.h
event.o: punto.h
file.o: buffer.h
file.o: file.h
file.o: punto.h
graphics.o: file.h
graphics.o: graphics.h
graphics.o: graphics-sdl.h
graphics.o: punto.h
graphics-sdl.o: fonts-1.xpm
graphics-sdl.o: graphics-sdl.h
help.o: help.h
maths.o: maths.h
maths.o: punto.h
punto: buffer.h
punto: event.h
punto: file.h
punto: graphics.h
punto: graphics-sdl.h
punto: help.h
punto: maths.h
punto: punto.h
punto: rgb.h
